const starterLibrary = [
  ["Magic in Mistletoe", "Janet Koops"],
  ["Wild Game", "Alisa Woods"],
  ["Save Me", "Molly Black"],
  ["Tanner", "Samantha Skye"],
  ["Vicious Lies", "Ella Miles"],
  ["Daddy's Arms", "Stella Moore"],
  ["The Tea Witch's Secret", "Laura Greenwood"],
  ["Ethan's Embrace", "Julie Ranse"],
  ["Zero Pucks Given", "Jessa York"],
  ["Broken Life", "Laura Rise"],
  ["The Rebound", "Sierra Hill"],
  ["Taming a Ruthless Heart", "Liz Gavin"],
  ["Danger in a Dive Bar", "Lori Sjoberg"],
  ["So Long", "Blake Pierce"],
  ["Hard Stick", "L.P. Dover"],
  ["Falling for the Forward", "Brenda Rothert"],
  ["One for Sorrow", "Sarah Denzil"],
  ["Wolf of Ash", "Amelia Shaw"],
  ["The Wolf Prince's Dangerous Mate", "Elysia Draven"],
  ["Wolf Signs", "Vivian Arend"],
  ["Wolf's Awakening", "Ava Blake"],
  ["Wolf's Bane", "Aimee Easterling"],
  ["A Wolf's True Mate", "Bella Lore"],
  ["The Wolf's Witch", "Rachel Medhurst"],
  ["Wild Pack (Books 1–3)", "Alisa Woods"],
  ["The Witch of the Prophecy", "Victoria Jayne"],
  ["The Witch Who Cried Wolf", "Sarah Makela"],
  ["Wolf Hunger", "Asa Maria Bradley"],
  ["The Wolf in the Window", "C.H. Jeffrey"],
  ["Wolf Kiss", "Christine DePetrillo"],
  ["Wolf Mated", "J.J. King"],
  ["Wolf Mated", "Tamsin Baker & Amelia Shaw"],
  ["Berkley Street", "Ron Ripley"],
  ["A Werewolf Jock for the New Year", "Isla Chiu"],
  ["Werewolves Only", "Carrie Pulkinen"],
  ["Wild Nights with a Lone Wolf", "Elisabeth Wheatley"],
  ["Taken: The Alpha's Captive", "V.M. Black"],
  ["A Tale of the Crimson Wolf", "Jennifer Carter"],
  ["The Tarot Witches (Books I–IV)", "S.M. Reine"],
  ["To Find a Mate", "Krystal Shannan"],
  ["Unawakened Fate", "Amanda Nichole"],
  ["Understanding Fate", "Amanda Nichole"],
  ["Viggo: The Obsession", "Charmaine Louise Shelton"],
  ["Wanted by the Wolf", "Bella Drake"],
  ["Owned by the Billionaires", "Drusilla Swan"],
  ["Ransom's Revenge", "Julie K. Cohen"],
  ["Lunar Curse", "Helena Secrow"],
  ["Scarlett Legacy", "Shibelli Rosewarne"],
  ["Shiftless", "Aimee Easterling"],
  ["Signy's Mates", "Charmaine Louise Shelton"],
  ["So I Married a Werewolf", "Kristen Strassel"],
  ["The Stone Wolf's Rejected Mate", "Cate C. Wells"],
  ["Stranded with the Wolf", "Marie Mason"],
  ["Geek Bear", "Scarlett Grove"],
  ["Her Lumberjack Bear Mate", "Arizona Tape"],
  ["Sheriff Bear", "Lauren Esker"],
  ["Blood Vowed", "Traci Douglass"],
  ["Christmas at the Marshmallow Café", "C.P. Ward"],
  ["How the Hitman Stole Christmas", "Katie Reus"],
  ["Hideaway Halloween", "Eliza Rockwood"],
  ["Tempt Me More", "Pippa Brook"],
  ["The Charming Storm Chaser", "Pippa Brook"],
  ["Just Next Door", "Sarah Everly"],
  ["Bear", "Reagan Phillips"],
  ["Tempting Mountain Man", "Kelsie Calloway"],
  ["Coffee & Kittens", "Christina Mattingly"],
  ["Battle Within", "Christina Mattingly"],
  ["Beautiful Storm", "Barbara Freethy"],
  ["King of Flames", "Kathryn Ann Kingsley"],
  ["To Kill a Fae", "Jamie A. Waters"],
  ["Hard to Love", "Willow Winters"],
  ["Claimed", "Em Brown"],
  ["Come Here Kitten", "Emilia Rose"],
  ["Prince of Wolves", "Quinn Loftis"],
  ["Finding My Shifter Soulmate", "Felicity West"],
  ["Born to Be Bound", "Addison Cain"],
  ["Bear Fur Hire", "T.S. Joyce"],
  ["Pitch Black", "Elise Noble"],
  ["The Alpha's Eternal Vow", "Parth Savaliya"],
  ["Moon Guardian", "J.R. Thorn"],
  ["The Billionaire's Secret Heart", "Ivy Layne"],
  ["Court of Vipers", "Jacqueline Pawl"],
  ["Elder Wolf", "Scarlett Grove"],
  ["Ink Cursed", "J.C. Diem"],
  ["Hidden", "Eliza Rockwood"],
  ["The Perfect Wife", "Blake Pierce"],
  ["Alpha Club", "Marata Eros"],
  ["Peripheral Vision", "A.S. Lorenzzen"],
  ["Crescent Pack: The Complete Series", "Jennifer Snyder"],
  ["Crimson Hate", "C.L. Reeder"],
  ["Nightfall", "Nicole Fox"],
  ["Rivers Between Us", "Greta Rose West"],
  ["Fae's Wolf", "Helen Walton"],
  ["The Wolf's Captive", "Mia Taylor"],
  ["Rejected by the Alpha", "Skye Wilson"],
  ["Her Forbidden Alpha", "Leigh Kelsey"],
  ["The Alpha's Second Chance", "Alicia Banks"],
  ["Marked by the Wolf", "Renee Rose"],
  ["The Rogue's Mate", "Harmony Raines"],
  ["Moon Chosen", "Aimee Easterling"],
  ["Wolf's Promise", "Nikki Jefford"],
  ["Alpha's Claim", "Lee Savino"],
  ["Bearly Mated", "Becca Fanning"],
  ["Feral Sins", "Suzanne Wright"],
  ["Carnal Secrets", "Suzanne Wright"],
  ["Wicked Cravings", "Suzanne Wright"],
  ["Dark Instincts", "Suzanne Wright"],
  ["Savage Urges", "Suzanne Wright"],
  ["Fierce Obsessions", "Suzanne Wright"],
  ["Lure of Oblivion", "Suzanne Wright"],
  ["Echoes of Fire", "Suzanne Wright"],
  ["When He's Sinful", "Suzanne Wright"],
  ["Shifter's Sacrifice", "Lisa Ladew"],
  ["Alpha Instinct", "Katie Reus"],
  ["Primal Possession", "Katie Reus"],
  ["Mating Instinct", "Katie Reus"],
  ["His to Protect", "Stacey Lynn"],
  ["Broken Howl", "Ann Gimpel"],
  ["Alpha's Temptation", "Renee Rose"],
  ["Wolf's Desire", "Terry Spear"],
  ["Big Bad Wolf", "Christine Warren"],
  ["Howl for Me", "Shelly Laurenston"],
  ["The Mane Event", "Shelly Laurenston"],
  ["Wolfsbane Hall", "Hazel Mack"],
  ["The Alpha's Witch", "T.S. Ryder"],
  ["Moon Marked", "Aimee Easterling"],
  ["Claimed by the Wolf King", "Luna Wilder"],
  ["The Wolf's Nanny", "Mia Brody"],
  ["Runaway Omega", "Ava Beringer"],
  ["Alpha's Secret Baby", "Scarlett Grove"],
  ["Wolf's Redemption", "Jen L. Grey"],
  ["Pack of Secrets", "Kate Rudolph"],
  ["The Cursed Alpha", "Brooke Kennedy"],
  ["Fated to the Bear", "Harmony Raines"],
  ["Bear's Fake Mate", "Skye MacKinnon"],
  ["The Dragon's Mate", "Harmony Raines"],
  ["Kiss of the Wolf", "Terry Spear"],
  ["Rejected No More", "Laxmi Hariharan"],
  ["The Alpha's Prize", "Roxy Sinclaire"],
  ["Mate Hunt", "Lola Glass"],
  ["The Wolf's Bride", "C.D. Gorri"],
  ["Moon Bound", "Cynthia Eden"],
  ["Shadow Pack", "T.S. Joyce"],
  ["Den of Sins", "Alta Hensley & Renee Rose"],
  ["Bewitching the Wolf", "Sophia Martin"],
  ["Billionaire Alpha Unclaimed Mate", "Myra V. Barton"],
  ["Broken Curse", "Jen L. Grey"],
  ["Chosen Wolf", "Jen L. Grey"],
  ["Claimed by the Alpha", "J. Raven Wilde"],
  ["Her Unforgotten Bear Mate", "Arizona Tape"],
  ["His Bear Hands", "Layla Nash"],
  ["Bear Mate", "Selina Coffey"],
  ["Bear Outlaw", "Candace Ayers"],
  ["Bear Temptation", "Novalee Swan"],
  ["Broken River", "Ruby Shae"],
  ["Flint", "Eva Kent"],
  ["12 Nights of Christmas", "Marie Landry"],
  ["The Billionaire's Christmas List", "Sophie Brooks"],
  ["Three Cowboy Christmas Wishes", "Lacy Williams"],
  ["Mortal Curse", "Unknown author"],
  ["The Vampire Prince", "Unknown author"],
  ["Prowling Their Mate", "Unknown author"],
  ["Blue Moon", "Unknown author"],
  ["Falling for the Grumpy Alpha", "Unknown author"],
  ["Fire, Brimstone and Chocolate Cake", "Unknown author"],
  ["Mated to the Capo", "Unknown author"],
  ["A Bittersweet Murder", "Unknown author"],
  ["The Witching Place", "Unknown author"],
  ["Shifter Mate Magic", "Unknown author"],
  ["Winter's Edge", "Unknown author"],
  ["Dad Bod Wolf Shifter", "Unknown author"],
  ["The Crimson Wolf", "Unknown author"],
  ["Her Werewolf Bodyguard", "Unknown author"],
  ["The Beast King's Bride", "Unknown author"],
  ["Darkhaven", "Unknown author"],
  ["Cruel Promise", "Unknown author"],
  ["Cruel Lord", "Unknown author"],
  ["A Witch's Call", "Unknown author"],
  ["Ursus Borealis", "Unknown author"],
  ["My Guardian Demon", "Unknown author"],
  ["Falling for Us Again", "Unknown author"],
  ["Secrets and Songbirds", "Unknown author"],
  ["Mated to the Wolf", "Unknown author"],
  ["Broods of Fenrir", "Unknown author"],
  ["Alpha Seeker", "Unknown author"],
  ["Greylock Manor", "Unknown author"],
  ["Blood Queen", "Unknown author"],
  ["The Shattered Court", "Unknown author"],
  ["Grave Water Lake", "Unknown author"],
  ["Jake", "Unknown author"],
  ["The Merman's Kiss", "Unknown author"],
  ["The Cinnamon Bun Book Store", "Unknown author"],
  ["Curse & Kingdom", "Unknown author"],
  ["Texas Forged", "Unknown author"],
  ["A Single Glance", "Unknown author"],
  ["Auctioned to the Bratva Brothers", "Unknown author"],
  ["Ruthless", "Unknown author"],
  ["The Darkest King", "Unknown author"],
  ["Savage Devotion", "Unknown author"],
  ["Crime Lord's Captive", "Unknown author"],
  ["The Devil in Disguise", "Unknown author"]
].map(([title, author], index) => ({
  id: `master-${index + 1}`,
  title,
  author,
  status: "tbr",
  rating: 0,
  notes: "",
  favorite: false
}));
